Added constructors to become C++20, fixed: implementation details leak in headers
minio/minio-cpp pull request #116
Opened 2024-03-17 14:26 UTC by HJLebbink

2024-03-18 13:54 UTC, balamurugana commented on examples/PutObject.cc
> +#include <fstream>
is this explicit declaration a standard or best practice?

2024-03-18 13:54 UTC, balamurugana commented on .gitattributes
> +*.sh test eol=lf
missing newline.

2024-03-18 16:21 UTC, balamurugana approved these changes

2024-03-18 19:34 UTC, kobalicek commented
After thinking about this I would probably change the pattern used in constructors to the following:

```
class X {
  some_type _a;
  some_type _b;

  X(some_type a, some_type b)
    _a(std::move(a)),
    _b(std::move(b)) {}
};
```

The reason is that with this design the user can actually decide which argument to move and which to copy. The copy is guaranteed to only happen once, so there is only the extra move per value, which seems okay to me.

2024-03-19 10:20 UTC, piotr-topnotch commented
> After thinking about this I would probably change the pattern used in constructors to the following:

I concur with this recommendation as being the least intrusive.

2024-03-19 10:44 UTC, piotr-topnotch requested changes

2024-03-19 14:17 UTC, merged